---
name: Setup nodes

on:
  workflow_dispatch:

jobs:
  setup_nodes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo 
      uses: actions/checkout@v3
      with:
        path: demo
    - name: Checkout hyphacoop/cosmos-ansible repo
      uses: actions/checkout@v3
      with:
        repository: hyphacoop/cosmos-ansible
        path: cosmos-ansible
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies Including Ansible
      run: |
        python -m pip install --upgrade pip
        if [ -f demo/requirements.txt ]; then pip install -r demo/requirements.txt; fi
    - name: Install dependencies Including Ansible
      run: |
        ansible-galaxy install -r cosmos-ansible/requirements.yml
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIV_KEY }}
        name: id_rsa # optional
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        if_key_exists: fail 
    - name: test / debug
      run: |
        ssh rjonczy@tendermint-node-0.demo.jonczy.dev ls /tmp
